#!/usr/bin/env php
<?php
use Xiag\DoctrineMappingTest\Command\TestCommand;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$application = new Application();
$application->add(new TestCommand());
$application->run();
